Reword the e2e test for the build action/workflow

diff --git a/.github/workflows/e2e.yml b/.github/workflows/e2e.yml
--- a/.github/workflows/e2e.yml
+++ b/.github/workflows/e2e.yml
@@ -27,10 +27,19 @@ jobs:
       module_base: "tests/test-failure"
 
   build_failure:
-    uses: "./.github/workflows/_internal_expected_build_failure.yml"
-    secrets: inherit
-    with:
-      module_base: "tests/build-failure"
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+      - uses: ./actions/build
+        with:
+          module_base: "tests/build-failure"
+        id: build_failure
+        continue-on-error: true
+      - name: Expect failure
+        run: |
+          echo "Expected the build_failure step to fail"
+          exit 1
+        if: ${{ failure() && steps.build_failure.outcome == 'failure' }}
 
   fmt_failure:
     uses: "./.github/workflows/_internal_expected_lint_failure.yml"
@@ -56,11 +65,20 @@ jobs:
       module_base: "tests/go1.20"
 
   build_version_mismatch_failure:
-    uses: "./.github/workflows/_internal_expected_build_failure.yml"
-    secrets: inherit
-    with:
-      go_version: "1.18"
-      module_base: "tests/go1.20"
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+      - uses: ./actions/build
+        with:
+          go_version: "1.18"
+          module_base: "tests/go1.20"
+        continue-on-error: true
+        id: build_failure
+      - name: Expect failure
+        run: |
+          echo "Expected the build_failure step to fail"
+          exit 1
+        if: ${{ failure() && steps.build_failure.outcome == 'failure' }}
 
   version_tests:
     uses: "./.github/workflows/ci_baseline_go_tests.yml"
